version: "3.8"

services:
  backend:
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    environment:
      FLASK_ENV: development
      FRONTEND_URL: "http://localhost:3000"
      BACKEND_URL: "http://localhost:4567"
      PORT: 4567
  frontend:
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
      PORT: 3000

networks: 
  internal-network:
    driver: bridge
    name: cruddur