install:
	pyenv local 3.12 && pyenv exec poetry install --no-root

# # Prepare environment and install dependencies
# setup-backend:
# 	cd backend-flask && python3.12 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt